# Generated by Django 5.2 on 2025-05-02 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_fooddonation_delete_donation'),
        ('users', '0008_alter_organization_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
            preserve_default=False,
        ),
    ]
