# Generated by Django 5.2 on 2025-05-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_fooddonation_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
