# Generated by Django 5.2 on 2025-04-27 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fooddonation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_organization',
        ),
        migrations.RemoveField(
            model_name='fooddonation',
            name='date',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('donor', 'Donor'), ('organization', 'Organization')], default='donor', max_length=20),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),

        migrations.AddField(
            model_name='fooddonation',
            name='is_organization',
            field=models.BooleanField(default=False),
        ),
         migrations.AddField(
            model_name='fooddonation',
            name='organization',
            field=models.ForeignKey(
            null=True,  # Allow null values for the organization field
            on_delete=django.db.models.deletion.CASCADE,
            related_name='received_donations',
            to=settings.AUTH_USER_MODEL),
        ),

        migrations.AlterField(
            model_name='fooddonation',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
