# Generated by Django 5.2 on 2025-05-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contact',
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
